[package]
name = "Rust-Crud"
version = "0.1.0"
authors = ["JosWambugu <josphatwambugu77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "1.0"
serde = "1.0"
serde_json = "1.0"